spring:
  profiles:
    active: dev
  application:
    name: APP_GATEWAY
  cloud:
    gateway:
      routes:
        - id: usersModule
          uri: lb://USERS
          predicates:
            - Path=/users/**
        - id: serviceProvidersModule
          uri: lb://PROVIDERS
          predicates:
            - Path=/providers/**
        - id: reviewAndStreaks
          uri: lb://REVIEWSTREAKS
          predicates:
            - Path=/review-streaks/**
logging:
  level:
    web: error
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

